name: polyglott_translator
description: Eine mehrsprachige Übersetzungs-App basierend auf GPT und Whisper.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  http: ^0.13.6
  http_parser: ^4.0.2
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  file_picker: ^5.3.1
  record: ^4.4.4
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  camera: ^0.10.5
  image_picker: ^0.8.7+5
  google_ml_kit: ^0.14.0
  flutter_tts: ^3.6.3
  device_info_plus: ^9.0.2
  connectivity_plus: ^4.0.1
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic 